export const ROLES = ['SUPER_ADMIN', 'ADMIN', 'DEPARTMENT_HEAD', 'AGENT', 'USER'];
export const COMPLAINT_STATUS = ['OPEN', 'IN_PROGRESS', 'PENDING', 'RESOLVED', 'CLOSED', 'REJECTED'];
export const COMPLAINT_PRIORITY = ['LOW', 'MEDIUM', 'HIGH', 'URGENT'];
